### ISSUE TITLE
Use the red bar as a menu?

### ISSUE THREAD

**Issue by darrencauthon** [kilt-cms/kilt-web-site#2]
![kilt-2](https://cloud.githubusercontent.com/assets/148768/3872059/63a736fe-210e-11e4-89bc-57ce24770f8b.jpg)

**Comment by timboisvert** [comment]
The problem I see with that is that the menu could get pretty sizable left and right if we add too many items to it. I'd prefer we keep the menu vertical to give us flexibility of growing it. I think if we're going to do anything with that space, I'd prefer we make a 3-link "Getting started" section. Like: 
1. $ gem 'kilt-cms'
2. Add 'require kilt' to your application.rb
3. $ rake kilt:install

**Comment by darrencauthon** [comment]
I agree -- I don't want too many pages... but I think we're going to need two or three pages.  In my mind right now:  the home page, a short Docs page, and an "examples" page that show how to do the most basic thing:  Write a new object, then show it on your Rails app. 

I'll think about the instructions idea.  I think that would be good, too, but I think we need some context around step (2) that might make it longer than what people would expect in that area.

I'll play with some ideas.

**Comment by darrencauthon** [comment]
I'm sorry :(

**Comment by timboisvert** [comment]
Haha no need to be sorry... Just cleaning up some old stuff.
