### ISSUE TITLE
Default username and pass?

### ISSUE THREAD

**Issue by darrencauthon** [kilt-cms/kilt-web-site#4]
Maybe use a different one? User/pass? Or a random cred?

**Comment by timboisvert** [comment]
Maybe "admin" for username and "changeme" for password. Then disallow that password in the authentication routine?

Tim

**Comment by darrencauthon** [comment]
How about... We use the default admin/changeme, but we put a warning header in the admin system itself? So they use kilt with these default settings, but they're reminded over-and-over to change the creds. 

My thought is that we want it to be as easy-as-possible to get Kilt going. I want to be able to tell them to install, then go to /admin and start administering their bagpipes.

**Comment by darrencauthon** [comment]
We could make the warning blink... That'll get under people's skin!

**Comment by timboisvert** [comment]
I'm down with just putting a warning at the top.
